name: Build
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: test
        run: |
          ping -6 -c 1 mill.growse.com
